application: tvupdt
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /update
  script: update.application
- url: /updatefaulty
  script: updatefaulty.application
- url: /addseries
  script: addseries.application
- url: /addfaultyseries
  script: addfaultyseries.application
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico
  
libraries:
- name: lxml
  version: "latest"
